# 默认参数相关
GB_BASE_DIR = "GB_BASE_DIR"
GB_RUN_TIME = "GB_RUN_TIME"
GB_VERSION = "GB_VERSION"
GB_DEBUG_FLAG = "GB_DEBUG_FLAG"

# 日志路径相关
GB_LOG_INFO_FILE = "GB_LOG_INFO_FILE"
GB_LOG_DEBUG_FILE = "GB_LOG_DEBUG_FILE"
GB_LOG_ERROR_FILE = "GB_LOG_ERROR_FILE"

GB_ACCESS_OK_FILE = "GB_ACCESS_OK_FILE"
GB_ACCESS_NO_FILE = "GB_ACCESS_NO_FILE"

GB_HISTORY_FORMAT = "GB_HISTORY_FORMAT"
GB_HISTORY_EXCLUDE = "GB_HISTORY_EXCLUDE"

GB_RESULT_DIR = "GB_RESULT_DIR"

# 输入参数相关
GB_TARGET = "GB_TARGET"

GB_MAX_URL_NUM = "GB_MAX_URL_NUM"
GB_MAX_ERROR_NUM = "GB_MAX_ERROR_NUM"

# 命中结果动态排除开关
GB_HIT_INFO_EXCLUDE = "GB_HIT_INFO_EXCLUDE"

# HTTP请求相关
GB_DEFAULT_PROTO = "GB_DEFAULT_PROTO"

GB_PROXIES = "GB_PROXIES"
GB_THREADS_COUNT = "GB_THREADS_COUNT"
GB_TASK_CHUNK_SIZE = "GB_TASK_CHUNK_SIZE"

GB_REQ_METHOD = "GB_REQ_METHOD"
GB_REQ_BODY = "GB_REQ_BODY"

GB_REQ_HEADERS = "GB_REQ_HEADERS"
GB_RANDOM_REQ_UA = "GB_RANDOM_REQ_UA"
GB_RANDOM_REQ_XFF = "GB_RANDOM_REQ_XFF"
GB_DYNA_REQ_HOST = "GB_DYNA_REQ_HOST"
GB_DYNA_REQ_REFER = "GB_DYNA_REQ_REFER"

GB_STREAM_MODE = "GB_STREAM_MODE"
GB_URL_ACCESS_TEST = "GB_URL_ACCESS_TEST"

GB_SPLIT_TARGET_PATH = "GB_SPLIT_TARGET_PATH"
GB_EXCLUDE_STATUS = "GB_EXCLUDE_STATUS"
GB_EXCLUDE_REGEXP = "GB_EXCLUDE_REGEXP"

GB_THREAD_SLEEP = "GB_THREAD_SLEEP"
GB_SSL_VERIFY = "GB_SSL_VERIFY"
GB_ALLOW_REDIRECTS = "GB_ALLOW_REDIRECTS"

# 扫描字典相关
GB_DICT_RULE_SCAN = "GB_DICT_RULE_SCAN"
GB_DICT_RULE_PATH = "GB_DICT_RULE_PATH"
GB_FREQUENCY_MIN = "GB_FREQUENCY_MIN"
GB_FREQUENCY_SYMBOL = "GB_FREQUENCY_SYMBOL"

GB_DICT_SUFFIX = "GB_DICT_SUFFIX"
GB_ONLY_SCAN_SPECIFY_EXT = "GB_ONLY_SCAN_SPECIFY_EXT"
GB_NO_SCAN_SPECIFY_EXT = "GB_NO_SCAN_SPECIFY_EXT"
GB_CUSTOM_URL_PREFIX = "GB_CUSTOM_URL_PREFIX"
GB_REMOVE_END_SYMBOLS = "GB_REMOVE_END_SYMBOLS"

GB_TIMEOUT = "GB_TIMEOUT"
GB_RETRY_TIMES = "GB_RETRY_TIMES"

# 其他常量
STR_BASE_PATH = "base_path"
STR_BASE_ROOT = "base_root"

# 未整理常量
GB_BASE_VAR_DIR = "GB_BASE_VAR_DIR"
GB_BASE_REPLACE_DICT = "GB_BASE_REPLACE_DICT"
GB_DEPENDENT_REPLACE_DICT = "GB_DEPENDENT_REPLACE_DICT"

GB_ANNOTATION_SYMBOL = "GB_ANNOTATION_SYMBOL"

GB_BASE_PATH_STR = "GB_BASE_PATH_STR"
GB_BASE_ROOT_STR = "GB_BASE_ROOT_STR"
GB_SCAN_BASE_PATH = "GB_SCAN_BASE_PATH"
GB_SCAN_BASE_ROOT = "GB_SCAN_BASE_ROOT"
GB_ANNOTATION_SYMBOL = "GB_ANNOTATION_SYMBOL"

GB_SYMBOL_REPLACE_DICT = "GB_SYMBOL_REPLACE_DICT"
GB_NOT_ALLOW_SYMBOL = "GB_NOT_ALLOW_SYMBOL"
GB_IGNORE_IP_FORMAT = "GB_IGNORE_IP_FORMAT"

GB_REMOVE_MULTI_SLASHES = "GB_REMOVE_MULTI_SLASHES"

GB_URL_PATH_LOWERCASE = "GB_URL_PATH_LOWERCASE"
GB_CHINESE_ENCODE = "GB_CHINESE_ENCODE"
GB_ONLY_ENCODE_CHINESE = "GB_ONLY_ENCODE_CHINESE"

# 命中结果保存
GB_SAVE_HIT_RESULT = "GB_SAVE_HIT_RESULT"
GB_HIT_OVER_CALC = "GB_HIT_OVER_CALC"
GB_HIT_EXT_FILE = "GB_HIT_EXT_FILE"
GB_HIT_PATH_FILE = "GB_HIT_PATH_FILE"
GB_HIT_DIR_FILE = "GB_HIT_DIR_FILE"
GB_HIT_FILE_FILE = "GB_HIT_FILE_FILE"
